services:
  - type: web
    name: safetyworkflows-map-hosting
    runtime: static
    buildCommand: npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: X-Frame-Options
        value: "SAMEORIGIN"
      - path: /*
        name: X-Content-Type-Options
        value: "nosniff"
      - path: /*
        name: Content-Security-Policy
        value: "upgrade-insecure-requests"

